# Copyright © 2025 Brent Tunnicliff <brent@tunnicliff.dev>

name: Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  xcodebuild:
    strategy:
      # Don't fail the other matrix values if one fails.
      fail-fast: false
      matrix:
        target: [
          { platform: "iOS", simulator_version: "26.2" },
          { platform: "tvOS", simulator_version: "26.2" },
          { platform: "watchOS", simulator_version: "26.2" },
          { platform: "visionOS", simulator_version: "26.2" },

          # macOS runs on the host and doesn't need a simulator.
          { platform: "macOS", simulator_version: "" }
        ]
    uses: Brent-Tunnicliff/workflow-common-apple/.github/workflows/xcodebuild.yml@path_to_v2
    with:
      platform: "${{ matrix.target.platform }}"
      runs_on: "macos-26"
      scheme: "lib-url-macro-swift-Package"
      simulator_version: "${{ matrix.target.simulator_version }}"
      # The macro tests only run on the host machine platform.
      skip_tests: ${{ matrix.target.platform != 'macOS' }}
      xcode_path: "/Applications/Xcode_26.3.app"

  swift:
    strategy:
      # Don't fail the other matrix values if one fails.
      fail-fast: false
      matrix:
        platform: [
          { name: "Linux", run_on: "ubuntu-latest" },
          { name: "macOS", run_on: "macos-latest" },
          { name: "Windows", run_on: "windows-latest" },
        ]
    runs-on: ${{ matrix.platform.run_on }}
    steps:
      - uses: SwiftyLab/setup-swift@latest
      - name: List environment variables
        shell: bash
        run: set
      - uses: actions/checkout@v4
      - name: Build package
        run: |
          swift build
      - name: Build tests
        run: |
          swift build --build-tests
      - name: Run tests
        run: |
          swift test --xunit-output .build/report
      - name: Upload test results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-${{ matrix.platform.name }}-swift.zip
          path: .build/report-swift-testing
          if-no-files-found: error
      - name: Check git status
        uses: Brent-Tunnicliff/action-git-status@v1

  lint:
    uses: Brent-Tunnicliff/workflow-common-apple/.github/workflows/lint.yml@path_to_v2
    with:
      runs_on: "macos-26"
