# Copyright © 2025 Brent Tunnicliff <brent@tunnicliff.dev>

name: Pipeline

on:
  push:
  workflow_dispatch:

env:
  PACKAGE_SCHEME: "lib-url-macro-swift-Package"

jobs:
  # xcodebuild:
  #   runs-on: macos-26
  #   strategy:
  #     # Don't fail the other matrix values if one fails.
  #     fail-fast: false
  #     matrix:
  #       target: [
  #         { platform: "iOS", simulator_version: "26.2" },
  #         { platform: "tvOS", simulator_version: "26.2" },
  #         { platform: "watchOS", simulator_version: "26.2" },
  #         { platform: "visionOS", simulator_version: "26.2" },

  #         # macOS runs on the host and doesn't need a simulator.
  #         { platform: "macOS", simulator_version: "" }
  #       ]
  #   steps:
  #     # ---------------------------
  #     # Setup
  #     # ---------------------------

  #     - name: Setup pipeline
  #       id: setup
  #       uses: Brent-Tunnicliff/action-setup-apple@v1
  #       with:
  #         platform: "${{ matrix.target.platform }}"
  #         simulator_version: "${{ matrix.target.simulator_version }}"
  #         xcode_path: "/Applications/Xcode_26.3.app"

  #     - name: Configure if tests can be run
  #       id: configure_if_tests_can_run
  #       env:
  #         PLATFORM: ${{ matrix.target.platform }}
  #       run: |
  #         if [[ $PLATFORM == "macOS" ]]; then
  #           CAN_TESTS_RUN="true"
  #         else
  #           CAN_TESTS_RUN="false"
  #         fi

  #         echo "can_tests_run: $CAN_TESTS_RUN"
  #         echo "can_tests_run=$CAN_TESTS_RUN" >> "$GITHUB_OUTPUT"

  #     # ---------------------------
  #     # Build and test package
  #     # ---------------------------

  #     - name: Build package debug
  #       env:
  #         DESTINATION: ${{ steps.setup.outputs.destination }}
  #       run: xcodebuild build
  #         -scheme "$PACKAGE_SCHEME"
  #         -destination "$DESTINATION"
  #         -configuration "Debug"
  #         -skipPackagePluginValidation
  #         CODE_SIGN_IDENTITY=""
  #         CODE_SIGNING_REQUIRED=NO

  #     - name: Build package tests
  #       if: ${{ steps.configure_if_tests_can_run.outputs.can_tests_run == 'true' }}
  #       env:
  #         DESTINATION: ${{ steps.setup.outputs.destination }}
  #       run: xcodebuild build-for-testing
  #         -scheme "$PACKAGE_SCHEME"
  #         -destination "$DESTINATION"
  #         -skipPackagePluginValidation
  #         CODE_SIGN_IDENTITY=""
  #         CODE_SIGNING_REQUIRED=NO

  #     - name: Run package tests
  #       if: ${{ steps.configure_if_tests_can_run.outputs.can_tests_run == 'true' }}
  #       env:
  #         DESTINATION: ${{ steps.setup.outputs.destination }}
  #         RESULTS_BUNDLE_PATH: ${{ steps.setup.outputs.test_results_path }}
  #       run: xcodebuild test-without-building
  #         -scheme "$PACKAGE_SCHEME"
  #         -destination "$DESTINATION"
  #         -resultBundlePath "$RESULTS_BUNDLE_PATH"
  #         CODE_SIGN_IDENTITY=""
  #         CODE_SIGNING_REQUIRED=NO

  #     - name: Upload test results
  #       if: ${{ steps.configure_if_tests_can_run.outputs.can_tests_run == 'true' && (success() || failure()) }}
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: "${{ steps.setup.outputs.test_results_file_name }}"
  #         path: "${{ steps.setup.outputs.test_results_path }}"
  #         if-no-files-found: error

  #     # Lets make sure it also builds in release configuration in case there are conditionals.
  #     - name: Build package release
  #       env:
  #         DESTINATION: ${{ steps.setup.outputs.destination }}
  #       run: xcodebuild build
  #         -scheme "$PACKAGE_SCHEME"
  #         -destination "$DESTINATION"
  #         -configuration "Release"
  #         -skipPackagePluginValidation
  #         CODE_SIGN_IDENTITY=""
  #         CODE_SIGNING_REQUIRED=NO

  #     # ---------------------------
  #     # Final checks
  #     # ---------------------------

  #     # Make sure there are no local changes as any auto generated changes must be checked into git.
  #     - name: Check git status
  #       uses: Brent-Tunnicliff/action-git-status@v1

  # swift-macos:
  #   name: "swift (macOS)"
  #   runs-on: macos-26
  #   steps:
  #     # List all environment variables to help with debugging possible issues.
  #     - name: List environment variables
  #       run: set
  #     - uses: actions/checkout@v4
  #     - name: Build package
  #       run: swift build
  #     - name: Build tests
  #       run: swift build --build-tests
  #     - name: Run tests
  #       run: swift test --xunit-output .build/report
  #     - name: Upload test results
  #       if: success() || failure()
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: test-macOS-swift.zip
  #         path: .build/report-swift-testing
  #         if-no-files-found: error
  #     - name: Check git status
  #       uses: Brent-Tunnicliff/action-git-status@v1

  # swift-linux:
  #   name: "swift (Linux)"
  #   runs-on: ubuntu-latest
  #   container:
  #     image: swift:6.2
  #   steps:
  #     - name: List environment variables
  #       run: set
  #     - uses: actions/checkout@v4
  #     - name: Build package
  #       run: swift build
  #     - name: Build tests
  #       run: swift build --build-tests
  #     - name: Run tests
  #       run: swift test --xunit-output .build/report
  #     - name: Upload test results
  #       if: success() || failure()
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: test-linux-swift.zip
  #         path: .build/report-swift-testing
  #         if-no-files-found: error
  #     - name: Check git status
  #       uses: Brent-Tunnicliff/action-git-status@v1

  swift-windows:
    name: "swift (Windows)"
    # Windows 2022 image already contains the dependencies we need.
    runs-on: windows-2022
    steps:
      - name: Install Swift
        run: |
          # Maybe I don't need this?
          # Change python to 3.10.*
          Set-Content -Path "$env:LOCALAPPDATA\py.ini" -Value "[defaults]", "python=3.10"
          Get-Content -Path "$env:LOCALAPPDATA\py.ini"
          py --version
          pip --version

          echo "Downloading swift installer..."
          Invoke-WebRequest -Uri https://download.swift.org/swift-6.2.4-release/windows10/swift-6.2.4-RELEASE/swift-6.2.4-RELEASE-windows10.exe -OutFile swift-installer.exe

          echo "Running swift installer..."
          Start-Process .\swift-installer.exe -ArgumentList '/quiet /norestart' -Wait

          echo "Adding swift.exe to path..."

          $swift = Get-ChildItem -Path $env:LOCALAPPDATA\Programs\Swift\Toolchains -Filter swift.exe -Recurse -ErrorAction SilentlyContinue -Force
          if (-not $swift) { 
            throw "swift.exe not found after install" 
          }

          echo "Swift found '$swift'"
          $swift_dir = Split-Path $swift.FullName
          echo "Adding to path: '$swift_dir'"
          $swift_dir >> $env:GITHUB_PATH

          echo "GITHUB_PATH:"
          Get-Content $env:GITHUB_PATH

          echo "Getting swift version:"
          & $swift --version
      - name: List environment variables
        shell: bash
        run: set
      # - uses: actions/checkout@v4
      # - name: Build package
      #   run: |
      #     swift --version
      #     swift build --verbose
      # - name: Build tests
      #   # env:
      #   #   SWIFT: ${{ steps.swift_path.outputs.path }}
      #   run: |
      #     # & $SWIFT build --build-tests
      # - name: Run tests
      #   # env:
      #   #   SWIFT: ${{ steps.swift_path.outputs.path }}
      #   run: |
      #     # & $SWIFT test --xunit-output .build/report
      # - name: Upload test results
      #   if: success() || failure()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: test-windows-swift.zip
      #     path: .build/report-swift-testing
      #     if-no-files-found: error
      # - name: Check git status
      #   uses: Brent-Tunnicliff/action-git-status@v1

  # lint:
  #   runs-on: macos-26
  #   steps:
  #     - name: List environment variables
  #       run: set
  #     - uses: actions/checkout@v4
  #     - name: Strict lint
  #       run: swift format lint . --recursive --parallel --strict
